### ISSUE TITLE
Document already exists

### ISSUE THREAD

**Issue by ile** [share/ShareJS#346]
This seems pretty important, so I'm creating it here also so that it gets noticed (added it [here](https://github.com/derbyjs/racer/issues/198) too).

This throws the error: http://todos.derbyjs.com/derby/

```
Ignoring attempt to ingest data in state floating doc.js:212
Operation was rejected (Document already exists). Trying to rollback change locally. doc.js:321
Error: Document already exists {stack: (...), message: "Document already exists"} microevent.js:45
Uncaught Error: Document already exists events.js:27
```

I noticed that code gets into this line (although there is this comment `"I don't think its possible to get here if we aren't in a floating state."`): https://github.com/share/ShareJS/blob/master/lib/client/doc.js#L888

**Comment by enjalot** [comment]
going to close here and track in racer
