### ISSUE TITLE
npm install outdated browser bundle in /dist folder (Windows)

### ISSUE THREAD

**Issue by Thylossus** [share/ShareJS#378]
Hi,

While I was trying to resolve an issue in my ShareJS application, I found that the browser bundle in the the ShareJS module's /dist folder is not up-to-date. I hat to run browserify myself to create a bundle based on the newest version (0.7.37).

I assume this problem is caused by Windows not supporting make. However, npm install displays neither a warning nor an error message.

For me this was quite a problem because the doc's _sendOpData function did not assign a sequence number to my operations.

**Comment by pedrosanta** [comment]
Yep, it seems to be outdated, yes. I've also had issues on #382.

Perhaps @nateps or @josephg could rebuild the lib and republish the package?

**Comment by pedrosanta** [comment]
Don't know if @jhchen could also do it...

**Comment by pedrosanta** [comment]
It seems that even on the last version 0.7.39 the dist lib is outdated, still throwing errors. (Refer to #382)

**Comment by josephg** [comment]
Ugh. Its because of this change from @Dignifiedquire: 43004c517b489de62db38f6d816d7972d19aad9e

The change rewrote the makefile, removing the `webclient` target for make. The package.json still tries to build the webclient target in a prepublish step, and thats not happening anymore.

**Comment by josephg** [comment]
I fixed the problem and published 0.7.40. Please confirm & reopen the issue if its still a problem.

**Comment by pedrosanta** [comment]
@josephg Works great! Awesome. :+1: :clap:
