### ISSUE TITLE
Contexts are removed because of `remove` method

### ISSUE THREAD

**Issue by jclem** [share/ShareJS#380]
Contexts have a [`remove` method on them](https://github.com/ottypes/text/blob/9ef1309a7ea4bf194fd8161e197eef7edc4f7dbd/lib/api.js#L34). When ShareJS [checks for `context.remove`](https://github.com/share/ShareJS/blame/c53a3b008c3e6ef8769dd883b0f423afb8743f8d/lib/client/doc.js#L685), it sees this method and assumes the context should be removed from the updatable contexts.

I'm not sure how I got into this state, but this is what's happening. Otherwise, only the first remote operation is applied :\

In my vendored `share.js`, I have updated this property to `shouldBeRemoved` not to clash with the `remove` method from the OT API that's merged into the context.

cc @Joris-van-der-Wel

**Comment by jclem** [comment]
I should add that I only `git blame`d because I assume someone else would have more understanding around that block of code than I do.

**Comment by Joris-van-der-Wel** [comment]
This issue never occurred before because the typo, that was fixed by my commit, caused contexts to never be removed from a Doc. 
I agree it should be renamed. IMO, the new version should be 0.8 (semver) because it is a public api.

**Comment by jclem** [comment]
I'm willing to accept that it wasn't a minor version bump since we're still sub-1.0.0, but I'll see if I have time for a quick PR to update this.

**Comment by pedrosanta** [comment]
Also happened to me. Commented out [`for` block](https://github.com/share/ShareJS/blame/c53a3b008c3e6ef8769dd883b0f423afb8743f8d/lib/client/doc.js#L685) to test it and make it work quick and dirty.

I also agree it should be renamed. `shouldBeRemoved` seems like an elegant, clear name to me as well.

**Comment by pedrosanta** [comment]
Found the commit that introduced the typo: fdd5085bfdf615a2f620be227095597a8abf3aa3
