### ISSUE TITLE
Instructions to run example not working, throwing "Op error: seq but not src"

### ISSUE THREAD

**Issue by pedrosanta** [share/ShareJS#382]
Hi there!

Downloaded ShareJS and tried to run the example server (following [the instructions](https://github.com/share/ShareJS#installing-and-running)) but isn't working.

Every operation seems to throw the error: `Op error: seq but not src (...)`.

Here's the output when I run `# coffee node_modules/share/examples/server.coffee`:

```
Listening on http://localhost:7007/
s->c  {"a":"init","protocol":0,"id":"d74bfb9b4a76107fd978c7ec19d42eca"}
c->s  {"a":"sub","c":"users","d":"seph"}
s->c  {"data":{"v":0},"a":"sub","c":"users","d":"seph"}
c->s  {"a":"op","v":0,"create":{"type":"text","data":null}}
Op error: seq but not src undefined undefined { src: 'd74bfb9b4a76107fd978c7ec19d42eca',
  seq: undefined,
  v: 0,
  create: { type: 'text', data: null },
  preValidate: undefined,
  validate: undefined } { channelPrefix: null }
s->c  {"a":"ack","error":"seq but not src"}
```

Can you confirm this issue? Any thoughts on it?

Cheers.

**EDIT:** Managed to make it work. It occurs because builtin lib on `/dist` folder on `npm` package is outdated (#378). Pasted a work around below.

**Comment by pedrosanta** [comment]
Ok, managed to fix the issue. Also confirmed that [the instructions given on README.md](https://github.com/share/ShareJS#installing-and-running) to run the example aren't working.

The error was occurring because I've installed the lib through npm, as described, and when I got missing modules running `examples/server.coffee` I installed them. And when it stopped complaining about modules, it fired out that error.

But, since #379 looked like a similiar issue, I did as @ygaradon and cloned the repository `master` branch, ran `npm install`, ran `make` (to build the dist folder/libraries needed for the client), and it 'worked'.

It 'worked' because, it only syncs the first character on each client and stops syncing after that, which I think it might be related to #380 (or even #333 and #332). Still going to figure this out better, though.

So to have the example 'running':

1. Clone the repository directly with `git clone git@github.com:share/ShareJS.git`, and `cd` into the 'ShareJS' folder. _Don't use `npm` version, as is broken at the moment!_
2. Run `npm install`.
3. Run `make` to build the share.js lib, used by the client.
4. Run `coffee examples/server.coffee` and open `http://localhost:7007`.

Probably I'll move the discussion about the `npm` version being broken to another issue, as it affects other stuff apparently.

Cheers.

**Comment by mauron85** [comment]
Thank you. Only wondering, when this will be merged.

**Comment by zcstarr** [comment]
Thanks @pedrosanta , I also would like this to be merged , just throwing in the support !

**Comment by pedrosanta** [comment]
Just tried to run this again, and instructions still don't work. :confused: 

So, since [`server.coffee`](https://github.com/share/ShareJS/blob/master/examples/server.coffee) still depends on lot of [`devDependencies`](https://github.com/share/ShareJS/blob/master/package.json#L25) (namely `browserchannel`, `connect`, `optimist ` and `serve-static`) these don't get installed when we install the package through NPM. So we still need to go into the share package folder and run `npm install` there.

But, it's also still throwing the `Op error: seq but not src (...)`, which I managed to circumvent by building the lib again. Probably it's something to do with the build process, or even, probably the build is being done on production and some `devDependencies` are needed. Just some thoughts.

So, an updated way to run the server example:

1. Do an `npm install share` as per the instructions. (If you've already installed the node package, skip to 2.)
2. `cd` to `share` package folder: `cd node_modules/share`.
3. Do an `npm install` to install also the `"devDependencies"` needed to rebuild the lib.
5. Rebuild the lib by running `make`.
6. `cd ../..` into your root dir, run `coffee node_modules/share/examples/server.coffee` and open `http://localhost:7007`.

**Comment by josephg** [comment]
Should be fixed now. Please confirm and reopen issue if its not.

**Comment by pedrosanta** [comment]
Yep, @josephg, npm package fixed. :+1: 

Although, again, the instructions don't still work because of missing packages. Looks like `server.coffee` needs some packages to run that are on the `devDependencies`. So I think we either add the info to install these on the instructions, or we add them to the `dependencies`.

The minimum required dependencies for the example server are:

```
npm install browserchannel connect serve-static optimist
```

But, since like, browserchannel it's optional for a server implementation and stuff, and those being only for the example to work, probably I'm more inclined to add that line to the instructions than adding those to `dependencies`.

Probably gonna keep this one closed, and make a PR with the updated README.
