### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by geakstr** [share/ShareJS#403]
Now the project is frozen?

**Comment by josephg** [comment]
Sharejs doesn't pay the bills. Or, any bills. I work on it when I have time.

**Comment by dilirst** [comment]
Sorry Dmitry, this project has been dead for a long time. Check out https://github.com/share/sharedb

**Comment by geakstr** [comment]
@dilirst hmm, right I understand ShareDB replaces ShareJS?

**Comment by dilirst** [comment]
Basically.

**Comment by josephg** [comment]
The plans for the future of the two projects is [on the mailing list](https://groups.google.com/forum/#!forum/sharejs).
